import sys
import numpy as np

# Script for finding the median of numbers in an output file
# generated by test_cpd_recovery.py.
# Ignore for any other purpose.
with open(sys.argv[1]) as f:
	f.readline()
	a=list(map(float, f.read().split('\n')[:-1]))
print(np.median(a))
